name: CI WorkFlow

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  checkout-code-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  formatting-code-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  linting-code-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  code-profiling-scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"


  code-scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"


  external-library-scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  unit-test-execute-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  code-coverage-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  build-artifact-create-job:
    needs:
      - checkout-code-job
      - formatting-code-check-job
      - linting-code-check-job
      - code-profiling-scan-job
      - code-scan-job
      - external-library-scan-job
      - unit-test-execute-job
      - code-coverage-check-job
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  build-image-create-job:
    needs: build-artifact-create-job
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  image-upload-job:
    needs: build-image-create-job
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"

  git-tag-create-job:
    needs: image-upload-job
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
